services:
  postgres:
    container_name: postgres-gerenciamento_faculdade
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=gerenciamento_faculdade
      - TZ=America/Sao_Paulo
    volumes:
      - postgres_v16:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - postgres-network
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-faculdade
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_v16:
    driver: local